project:
  type: website
  output-dir: docs

website:
  title: "장일준 포트폴리오 페이지"
  navbar:
    left:
        - href: index.qmd
          text: Home
        - href: posts/index.qmd
          text: All posts


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



