project:
  type: website
  output-dir: docs

website:
  title: "장일준"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: hw1.qmd
        text: home work 1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



