project:
  type: website
  output-dir: docs

website:
  title: "장일준 포트폴리오 페이지"
  navbar:
    left:
        - href: index.qmd
          text: Home
        - href: blog.qmd
          text: Blog


format:
  html:
    theme: cosmo
    toc: true



